# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [2]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [3]:
my_array1 = np.array([1,2,3,4,5])
print(my_array1.shape)
print(my_array1.dtype)

my_array2 = np.array([1, 'two', 3,'four',5])
print(my_array2.shape)
print(my_array2.dtype)

##the data type for the 1st array is integers and for the 2nd array they are  Unicode string data type where the maximum length of the string is 21

(5,)
int64
(5,)
<U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [4]:
my_array3 = np.array([1,2,3,4,5,6,6,7,8,])
print(my_array3.shape)
print(my_array3.dtype)

##the first number in size represents how many columns the array has and the second is the number of rows

(9,)
int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features.

Print the shape of the array.

In [5]:
# already defined first and second inputs
num_samples = 100
num_features = 17

my_array6 = np.random.random((num_samples,num_features))
print(my_array6.shape)

(100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [6]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

my_array5 = np.random.random((num_images, num_rows, num_cols, num_channels))
print(my_array5.shape)

(100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [7]:
my_array4 = np.array([[1,2],
                      [3,4],
                      [5,6]])
print(my_array4.shape)
sum_of_array = np.sum(my_array4)
print(sum_of_array)
sum_by_col = np.sum(my_array4, axis = 0)
print(sum_by_col)
sum_by_row = np.sum(my_array4, axis = 1, dtype = float)
print(sum_by_row)
print(my_array4[0])
print(my_array4[1])
print(my_array4[1,0])
my_array4[2,1] = 10
print(my_array4[2,1])

for row in range(my_array4.shape[0]):
    for col in range(my_array4.shape[1]):
      print(my_array4[row,col])

(3, 2)
21
[ 9 12]
[ 3.  7. 11.]
[1 2]
[3 4]
3
10
1
2
3
4
5
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [8]:
import numpy as np
from numpy import random

np_a = np.random.rand(3,2)

print(np_a)

years_list = np.arange(start=1991, stop=2018)

print(years_list)

empty_np = np.empty((3,5,10))

print(empty_np)

one_array = np.ones([3,5,10])

print(one_array)

ones_array = np.ones([3,5,10])
const_array = ones_array * 5

print(const_array)

x = random.normal(0,1,10)
print(x)

[[0.59128204 0.7636693 ]
 [0.2759459  0.17324981]
 [0.41849905 0.05997636]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
[[[6.83365523e-310 6.83365523e-310 5.04869566e-310 5.04869566e-310
   0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 6.83359167e-310
   6.83359167e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000 0.00000000e+000 0.00

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [9]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [13]:
years_3d = np.array([[1,1],[2,2],[3,3],
                     [4,4],[5,5],[6,6],
                     [7,7],[8,8],[9,9],
                     ])

print(years_3d.shape)

years_1d = years_3d.flatten()

print(years_1d.shape)

years_2d = years_1d[np.newaxis, :]

print(years_2d.shape)

years_1d = np.squeeze(years_2d)

print(years_1d.shape)

(9, 2)
(18,)
(1, 18)
[[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]]
(18,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [23]:
ones_array = np.ones([2,3], dtype = int)

twos_array = np.full([2,3], 2)

ones_1d_array = np.ones(3, int)

ones_2d_array = np.full(3, 2)

one_and_two_array = np.concatenate([ones_array, twos_array])
print(one_and_two_array)

one_and_two_array = np.concatenate([ones_array, twos_array], axis = 0)
print(one_and_two_array)

one_and_two_array = np.concatenate([ones_array, twos_array], axis = 1)
print(one_and_two_array)

one_and_two_array = np.concatenate([ones_1d_array, ones_2d_array])
print(one_and_two_array)

oned_stack_array = np.stack([ones_array,twos_array])
print(oned_stack_array)

oned_stack_array = np.stack([ones_1d_array,ones_2d_array],0)
print(oned_stack_array)

oned_stack_array = np.stack([ones_1d_array,ones_2d_array],1)
print(oned_stack_array)

oned_stack_array = np.stack([ones_1d_array,ones_2d_array],1)
print(oned_stack_array)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
[1 1 1 2 2 2]
[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]
[[1 1 1]
 [2 2 2]]
[[1 2]
 [1 2]
 [1 2]]
[[1 2]
 [1 2]
 [1 2]]


---
#### <span style="color:chocolate">Numpy broadcasting</span>

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [27]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [25]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [28]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [29]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [30]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.8792638 , 0.78168196, 0.91451649, 0.82082677],
       [0.82644074, 0.70875517, 0.15741544, 0.07559924],
       [0.56539834, 0.33816029, 0.3107597 , 0.17954344],
       [0.60226188, 0.50371148, 0.55595577, 0.95475503],
       [0.44550258, 0.63723361, 0.14834832, 0.75831421],
       [0.93937512, 0.55671129, 0.96523987, 0.82303153],
       [0.56111664, 0.50347923, 0.59403819, 0.17216454],
       [0.61583332, 0.796161  , 0.10744158, 0.79752413],
       [0.16244155, 0.55324795, 0.28789393, 0.6823116 ],
       [0.6313923 , 0.59079689, 0.94720144, 0.72229978]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [37]:
np.random.seed(seed=1)

mean_of_col = np.mean(my_array, axis = 0, keepdims=True)
print(mean_of_col)

std_of_col = np.std(my_array, axis = 0, keepdims=True)
print(std_of_col)

standardized_array = (my_array - mean_of_col) / std_of_col
print(standardized_array)
print(standardized_array.shape)

[[0.62290263 0.59699389 0.49888107 0.59863703]]
[[0.2141194  0.13262853 0.3280471  0.30740441]]
[[ 1.19728139  1.39252143  1.26699923  0.72279295]
 [ 0.9505823   0.84266399 -1.04090431 -1.70146479]
 [-0.26856179 -1.95156801 -0.57345843 -1.36332975]
 [-0.0963983  -0.70333592  0.17398324  1.15846744]
 [-0.82850991  0.30340169 -1.068544    0.51943685]
 [ 1.4780188  -0.30372497  1.42162148  0.72996512]
 [-0.28855857 -0.705087    0.29007153 -1.38733364]
 [-0.03301573  1.50169134 -1.19324176  0.64698844]
 [-2.15048741 -0.32983809 -0.64316113  0.27219706]
 [ 0.03964923 -0.04672447  1.36663415  0.40228033]]
(10, 4)


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [38]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [50]:
image_copy = my_image[1:-1, 1:-1]
print(image_copy)

image_copy = my_image[2:-2, 2:-2]
print(image_copy)

reversed = my_image[:, ::-1]
print(reversed)

image = my_image.copy()
image[::2,::2] = 0.5
print(image)

[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
[[0.48]]
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
[[0.5  0.04 0.5  0.12 0.5 ]
 [0.2  0.24 0.28 0.32 0.36]
 [0.5  0.44 0.5  0.52 0.5 ]
 [0.6  0.64 0.68 0.72 0.76]
 [0.5  0.84 0.5  0.92 0.5 ]]
